### ISSUE TITLE
Could not get a reverse shell with HTTPS

### ISSUE THREAD

**Issue by alexonk** [chrispetrou/HRShell#3] opened 2020-04-18 16:56 UTC
Hi, I tried to obtain a shell with HTTP, it worked. 
On the other hand, I have followed all steps provided to try to obtain a shell with HTTPS but no result.
Could you please verify if that is working? Thank you
It is still a great tool nonetheless.

**Comment by chrispetrou** [comment] 2020-04-20 09:52
Hi @alexonk - I tried with HTTPS and I can confirm (_using wireshark_) that it works for me. Could you please describe with a bit more detail what kind of error you are getting?

__Note 1:__ In case you decide to establish an HTTPS connection, the url you'll have to provide to the client must be in the form of "__https://...__" - if you use http in the url then it won't work.

__Note 2:__ In case you didn't use client.py as client and coded yours - you must either pass the appropriate certificate of disable SSL verification - but that only in case you didn't esu the client provided.

**Comment by chrispetrou** [comment] 2020-05-22 10:05
Hi @alexonk 
Did you manage to resolve the issues with the notes I provided above - any feedback is appreciated...

**Comment by chrispetrou** [comment] 2020-06-09 13:12
Closing since I cannot reproduce and got no feedback. If anyone in the future face the same problem feel free to reopen the issue __but__ in that case please provide [some additional info](https://github.com/chrispetrou/HRShell/issues/3#issuecomment-616439259).

**Closed by chrispetrou** 2020-06-09 13:13 UTC
Labels: Possibly Invalid
