### ISSUE TITLE
TLS Error

### ISSUE THREAD

**Issue by sparta34** [chrispetrou/HRShell#1] opened 2019-09-21 00:14 UTC
**Describe the bug**
when a launch the server using tornado  argument like this : 
python3 server.py --host https://192.168.1.113  --cert cert.pem  --key key.pem -p 17 -s tornado
it gives this error
* Serving on: https://https://192.168.1.113:17
Traceback (most recent call last):
  File "server.py", line 337, in <module>
    ssl_ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
NameError: name 'ssl' is not defined

**Device information:**
 - OS: kali linux 2019.3 64bits
 - python 3.7

**Comment by chrispetrou** [comment] 2019-09-21 09:17
@sparta34 Did you install pyopenssl from requirements.txt? I ask that because I had forgotten to add it to requirements.txt till the latest versions. Also try to open a python3-interactive shell and try the following import:
```
>>> from ssl import create_default_context
```
Does it produce any error?

Also when using `--host` argument you just have to provide the IP, the scheme (`http` or `https`) will be decided and depends on other arguments, in your case since you'll use a cert/key pair it's going to be `https`. So it should be `--host 192.168.1.3`.

**Comment by sparta34** [comment] 2019-09-21 12:10
yes i have installed pyopenssl and i tried this import >>> from ssl import create_default_context
but i still get this error only when i choose  -s tornado using TLS !

**Comment by chrispetrou** [comment] 2019-09-21 14:32
@sparta34 You were right about the bug - I confirmed it. The problem was I had forgotten to import ssl on `server.py` script. I fixed it now so it should work fine:

![screenshot](https://user-images.githubusercontent.com/36112975/65374697-70aaf280-dc95-11e9-8ce4-e7e157ced520.png)

Please update `server.py` to the latest version and check again to confirm it's working on your side also so I can close the issue! Thank you very much for reporting this!

**Comment by sparta34** [comment] 2019-09-21 16:37
it is working now, thanks for your time keep up the good job bravo

**Closed** 2019-09-21 17:02 UTC
